#pragma once

#include "types.h"
#include "order.h"
#include "level.h"
#include "pool_allocator.h"

#include <map>
#include <unordered_map>
#include <vector>
#include <functional>

namespace lob {

class OrderBook {
public:
    OrderBook();
    ~OrderBook();

    // Core operations
    // Returns trades generated by this order
    std::vector<Trade> add_order(OrderId id, Side side, Price price, Quantity qty, Timestamp ts);

    // Cancel an existing order — returns true if found and removed
    bool cancel_order(OrderId id);

    // Modify an order (cancel + re-add under same ID)
    std::vector<Trade> modify_order(OrderId id, Price new_price, Quantity new_qty, Timestamp ts);

    // Queries
    Price best_bid() const;
    Price best_ask() const;
    Price spread() const;

    Quantity volume_at(Side side, Price price) const;
    size_t order_count() const { return orders_.size(); }

    bool empty() const { return orders_.empty(); }

private:
    // Match an incoming order against the opposite side
    std::vector<Trade> match(Order* incoming, Timestamp ts);

    // Insert a resting order into the book
    void insert_order(Order* order);

    // Remove order from its level and clean up empty levels
    void remove_order(Order* order);

    // Bids: highest price first (std::greater)
    std::map<Price, Level, std::greater<Price>> bids_;

    // Asks: lowest price first (std::less — default)
    std::map<Price, Level> asks_;

    // Fast lookup: OrderId → Order pointer (for cancel/modify)
    std::unordered_map<OrderId, Order*> orders_;

    // Memory pool for Order objects
    PoolAllocator<Order> pool_;
};

} // namespace lob
